// Mock data for testing Phase 2.1 components without backend
import type { DoctorStatistics, Appointment, Prescription } from '../store/api';

export const mockDoctorStatistics: DoctorStatistics = {
  total_patients: 156,
  total_appointments: 89,
  total_prescriptions: 134,
  appointments_today: 8,
  prescriptions_today: 12,
  upcoming_appointments: 15,
  completed_appointments_today: 5,
  pending_appointments_today: 3,
};

export const mockTodayAppointments: Appointment[] = [
  {
    id: 'apt-001',
    appointment_number: 'APT001',
    doctor_id: 'doc-123',
    patient_mobile_number: '9876543210',
    patient_first_name: 'John',
    patient_last_name: 'Doe',
    patient_full_name: 'John Doe',
    appointment_date: '2025-10-31',
    appointment_time: '10:00',
    appointment_datetime: '2025-10-31T10:00:00Z',
    duration_minutes: 30,
    status: 'scheduled',
    reason_for_visit: 'Regular checkup and blood pressure monitoring',
    notes: 'Patient has been experiencing mild headaches',
    created_at: '2025-10-30T15:30:00Z',
    updated_at: '2025-10-30T15:30:00Z',
  },
  {
    id: 'apt-002',
    appointment_number: 'APT002',
    doctor_id: 'doc-123',
    patient_mobile_number: '9876543211',
    patient_first_name: 'Jane',
    patient_last_name: 'Smith',
    patient_full_name: 'Jane Smith',
    appointment_date: '2025-10-31',
    appointment_time: '11:30',
    appointment_datetime: '2025-10-31T11:30:00Z',
    duration_minutes: 45,
    status: 'in_progress',
    reason_for_visit: 'Follow-up for diabetes management',
    notes: 'Review lab results and adjust medication',
    created_at: '2025-10-29T09:15:00Z',
    updated_at: '2025-10-31T11:30:00Z',
  },
  {
    id: 'apt-003',
    appointment_number: 'APT003',
    doctor_id: 'doc-123',
    patient_mobile_number: '9876543212',
    patient_first_name: 'Robert',
    patient_last_name: 'Johnson',
    patient_full_name: 'Robert Johnson',
    appointment_date: '2025-10-31',
    appointment_time: '14:00',
    appointment_datetime: '2025-10-31T14:00:00Z',
    duration_minutes: 30,
    status: 'scheduled',
    reason_for_visit: 'Consultation for back pain',
    notes: 'Referred by orthopedist',
    created_at: '2025-10-28T12:00:00Z',
    updated_at: '2025-10-28T12:00:00Z',
  },
];

export const mockRecentPrescriptions: Prescription[] = [
  {
    id: 'rx-001',
    prescription_number: 'RX001',
    doctor_id: 'doc-123',
    patient_mobile_number: '9876543210',
    patient_first_name: 'John',
    patient_last_name: 'Doe',
    patient_full_name: 'John Doe',
    appointment_id: 'apt-001',
    chief_complaint: 'Headache and fatigue',
    symptoms: 'Persistent headache for 3 days, mild fatigue',
    clinical_notes: 'Blood pressure slightly elevated. Patient appears tired.',
    diagnosis: 'Hypertension - mild, tension headache',
    doctor_instructions: 'Take medication as prescribed, reduce stress, regular exercise',
    total_amount: 1250.00,
    status: 'finalized',
    created_at: '2025-10-30T16:00:00Z',
    updated_at: '2025-10-30T16:00:00Z',
  },
  {
    id: 'rx-002',
    prescription_number: 'RX002',
    doctor_id: 'doc-123',
    patient_mobile_number: '9876543211',
    patient_first_name: 'Jane',
    patient_last_name: 'Smith',
    patient_full_name: 'Jane Smith',
    appointment_id: 'apt-002',
    chief_complaint: 'Blood sugar control',
    symptoms: 'Elevated blood glucose readings',
    clinical_notes: 'HbA1c: 8.2%, requires medication adjustment',
    diagnosis: 'Type 2 Diabetes Mellitus - uncontrolled',
    doctor_instructions: 'Continue metformin, add insulin, monitor blood glucose daily',
    total_amount: 2800.00,
    status: 'dispensed',
    created_at: '2025-10-29T17:30:00Z',
    updated_at: '2025-10-30T10:00:00Z',
  },
  {
    id: 'rx-003',
    prescription_number: 'RX003',
    doctor_id: 'doc-123',
    patient_mobile_number: '9876543213',
    patient_first_name: 'Alice',
    patient_last_name: 'Brown',
    patient_full_name: 'Alice Brown',
    chief_complaint: 'Respiratory infection',
    symptoms: 'Cough, fever, chest congestion',
    clinical_notes: 'Chest examination shows mild congestion, no wheezing',
    diagnosis: 'Upper respiratory tract infection',
    doctor_instructions: 'Complete antibiotic course, rest, plenty of fluids',
    total_amount: 850.00,
    status: 'completed',
    created_at: '2025-10-28T14:45:00Z',
    updated_at: '2025-10-29T09:00:00Z',
  },
];