"""
Case Study Model
For AI-generated treatment case studies (doctor-only feature)
"""

from sqlalchemy import Column, String, Text, Boolean, Date, ForeignKey, UUID, TIMESTAMP
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func

from app.core.database import Base


class CaseStudy(Base):
    """
    Case Study Model - AI-Generated Treatment Documentation

    Stores presentation-ready case studies generated by LLM
    from patient treatment data (appointments, procedures, observations)
    """
    __tablename__ = "case_studies"

    # Primary Key
    id = Column(UUID, primary_key=True, server_default=func.gen_random_uuid())

    # Unique Identifier
    case_study_number = Column(String(100), unique=True, nullable=False, index=True)

    # Patient Reference (Composite Key)
    patient_mobile_number = Column(String(15), nullable=False)
    patient_first_name = Column(String(100), nullable=False)
    patient_uuid = Column(UUID, ForeignKey("patients.id"), nullable=False)

    # Doctor Reference
    doctor_id = Column(UUID, ForeignKey("doctors.id"), nullable=False)

    # Related Entities (Treatment Journey) - JSON arrays stored as text
    appointment_ids = Column(Text, nullable=True)  # JSON array of UUIDs
    prescription_ids = Column(Text, nullable=True)  # JSON array of UUIDs
    procedure_ids = Column(Text, nullable=True)  # JSON array of UUIDs
    observation_ids = Column(Text, nullable=True)  # JSON array of UUIDs (added for dental observations)

    # Case Study Content
    title = Column(String(500), nullable=False)
    chief_complaint = Column(Text, nullable=False)

    # Pre-Treatment Assessment (AI-Generated)
    pre_treatment_summary = Column(Text, nullable=True)
    initial_diagnosis = Column(Text, nullable=True)
    treatment_goals = Column(Text, nullable=True)

    # Treatment Timeline (AI-Generated)
    treatment_summary = Column(Text, nullable=True)
    procedures_performed = Column(Text, nullable=True)

    # Post-Treatment Outcome (AI-Generated)
    outcome_summary = Column(Text, nullable=True)
    success_metrics = Column(Text, nullable=True)
    patient_feedback = Column(Text, nullable=True)

    # Full Case Study Narrative (AI-Generated)
    full_narrative = Column(Text, nullable=True)

    # Metadata
    generation_prompt = Column(Text, nullable=True)  # Prompt used for LLM
    generation_model = Column(String(100), nullable=True)  # e.g., "claude-sonnet-4"

    # Timeline
    treatment_start_date = Column(Date, nullable=True)
    treatment_end_date = Column(Date, nullable=True)

    # Status
    status = Column(String(20), nullable=False, server_default="draft")
    # ENUM: 'draft', 'finalized', 'archived'

    # Export/Presentation
    is_exported = Column(Boolean, nullable=False, server_default="false")
    exported_format = Column(String(20), nullable=True)  # 'pdf', 'docx', 'pptx'
    exported_at = Column(TIMESTAMP, nullable=True)

    # Audit Fields
    created_at = Column(TIMESTAMP, server_default=func.now(), nullable=False)
    updated_at = Column(TIMESTAMP, server_default=func.now(), onupdate=func.now(), nullable=False)
    created_by = Column(UUID, nullable=True)
    is_active = Column(Boolean, nullable=False, server_default="true")

    # Relationships
    patient = relationship("Patient", foreign_keys=[patient_uuid])
    doctor = relationship("Doctor", foreign_keys=[doctor_id])
    attachments = relationship("DentalAttachment", back_populates="case_study", foreign_keys="DentalAttachment.case_study_id")

    def __repr__(self):
        return f"<CaseStudy {self.case_study_number} - {self.title}>"
