"""Add is_active column to dental_observations and dental_procedures

Revision ID: 53cebb2ea904
Revises: 
Create Date: 2025-12-18 13:04:10.967318+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '53cebb2ea904'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointments', 'office_id',
               existing_type=sa.VARCHAR(length=50),
               comment="Office ID from doctor's offices array",
               existing_nullable=True)
    op.alter_column('dental_observation_templates', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.add_column('dental_observations', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.add_column('dental_procedures', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.alter_column('doctors', 'clinic_address',
               existing_type=sa.TEXT(),
               comment='Clinic or hospital address (deprecated - use offices)',
               existing_comment='Clinic or hospital address',
               existing_nullable=True)
    op.alter_column('doctors', 'offices',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               comment='List of office locations with name and address',
               existing_nullable=True)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               comment='Hashed password for local authentication',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Hashed password for local authentication',
               existing_nullable=True)
    op.alter_column('doctors', 'offices',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'[]'::jsonb"),
               comment=None,
               existing_comment='List of office locations with name and address',
               existing_nullable=True)
    op.alter_column('doctors', 'clinic_address',
               existing_type=sa.TEXT(),
               comment='Clinic or hospital address',
               existing_comment='Clinic or hospital address (deprecated - use offices)',
               existing_nullable=True)
    op.drop_column('dental_procedures', 'is_active')
    op.drop_column('dental_observations', 'is_active')
    op.alter_column('dental_observation_templates', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('appointments', 'office_id',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment="Office ID from doctor's offices array",
               existing_nullable=True)
    # ### end Alembic commands ###